import type { AppLocale } from '../i18n';

// Orden: es, en, fr, de, it, pt, nl, pl.
const rows: Record<string, readonly [string, string, string, string, string, string, string, string]> = {
  'auth.loading': ['Cargando sesión...', 'Loading session...', 'Chargement de la session...', 'Sitzung wird geladen...', 'Caricamento sessione...', 'A carregar sessão...', 'Sessie laden...', 'Ładowanie sesji...'],
  'auth.subtitle': ['Accede a tu cuenta o crea una nueva', 'Sign in to your account or create a new one', 'Connectez-vous ou créez un compte', 'Melde dich an oder erstelle ein neues Konto', 'Accedi al tuo account o creane uno nuovo', 'Inicie sessão ou crie uma conta nova', 'Log in of maak een nieuw account aan', 'Zaloguj się lub utwórz nowe konto'],
  'auth.tabLogin': ['Iniciar sesión', 'Sign in', 'Se connecter', 'Anmelden', 'Accedi', 'Iniciar sessão', 'Inloggen', 'Zaloguj się'],
  'auth.tabRegister': ['Crear cuenta', 'Create account', 'Créer un compte', 'Konto erstellen', 'Crea account', 'Criar conta', 'Account aanmaken', 'Utwórz konto'],
  'auth.submitLogin': ['Entrar', 'Sign in', 'Se connecter', 'Anmelden', 'Entra', 'Entrar', 'Inloggen', 'Zaloguj'],
  'auth.submitRegister': ['Crear cuenta', 'Create account', 'Créer le compte', 'Konto erstellen', 'Crea account', 'Criar conta', 'Account aanmaken', 'Utwórz konto'],
  'auth.submitting': ['Un momento...', 'One moment...', 'Un instant...', 'Einen Moment...', 'Un momento...', 'Um momento...', 'Een moment...', 'Chwileczkę...'],
  'auth.preparingDevice': ['Preparando este dispositivo...', 'Preparing this device...', 'Préparation de cet appareil...', 'Gerät wird vorbereitet...', 'Preparazione del dispositivo...', 'A preparar este dispositivo...', 'Dit apparaat wordt voorbereid...', 'Przygotowywanie urządzenia...'],
  'auth.deviceUnavailable': ['No se pudo crear el identificador seguro de este dispositivo. Reinicia la app: sin él no se puede acceder.', 'Could not create this device’s secure identifier. Restart the app: access is not possible without it.', 'Impossible de créer l’identifiant sécurisé de cet appareil. Redémarrez l’application : l’accès est impossible sans lui.', 'Die sichere Gerätekennung konnte nicht erstellt werden. Starte die App neu: Ohne sie ist kein Zugang möglich.', 'Impossibile creare l’identificativo sicuro del dispositivo. Riavvia l’app: senza di esso non è possibile accedere.', 'Não foi possível criar o identificador seguro deste dispositivo. Reinicie a app: sem ele não é possível aceder.', 'De beveiligde apparaat-ID kon niet worden aangemaakt. Start de app opnieuw: zonder ID is toegang niet mogelijk.', 'Nie udało się utworzyć bezpiecznego identyfikatora urządzenia. Uruchom aplikację ponownie: bez niego dostęp jest niemożliwy.'],
  'auth.rolePrincipal': ['Soy principal', 'I am the main user', 'Je suis l’utilisateur principal', 'Ich bin Hauptbenutzer', 'Sono l’utente principale', 'Sou o utilizador principal', 'Ik ben de hoofdgebruiker', 'Jestem głównym użytkownikiem'],
  'auth.roleEmployee': ['Soy usuario adicional', 'I am an additional user', 'Je suis un utilisateur supplémentaire', 'Ich bin zusätzlicher Benutzer', 'Sono un utente aggiuntivo', 'Sou um utilizador adicional', 'Ik ben een extra gebruiker', 'Jestem dodatkowym użytkownikiem'],
  'auth.changeRole': ['Cambiar tipo de usuario', 'Change user type', 'Changer de type d’utilisateur', 'Benutzertyp ändern', 'Cambia tipo di utente', 'Alterar tipo de utilizador', 'Gebruikerstype wijzigen', 'Zmień typ użytkownika'],
  'auth.companyEmail': ['Correo de la empresa (usuario principal)', 'Company email (main user)', 'E-mail de l’entreprise (utilisateur principal)', 'E-Mail des Unternehmens (Hauptbenutzer)', 'Email dell’azienda (utente principale)', 'Email da empresa (utilizador principal)', 'E-mailadres van het bedrijf (hoofdgebruiker)', 'E-mail firmy (główny użytkownik)'],
  'auth.employeeHint': ['Introduce el código que te ha dado el usuario principal. Tu cuenta se unirá a su empresa y solo tendrá acceso al TPV.', 'Enter the code the main user gave you. Your account will join their business with POS access only.', 'Saisissez le code fourni par l’utilisateur principal. Votre compte rejoindra son entreprise avec un accès au TPV uniquement.', 'Gib den Code des Hauptbenutzers ein. Dein Konto wird seinem Unternehmen zugeordnet und hat nur Kassenzugriff.', 'Inserisci il codice fornito dall’utente principale. Il tuo account entrerà nella sua azienda con accesso solo al POS.', 'Introduza o código dado pelo utilizador principal. A sua conta junta-se à empresa dele com acesso apenas ao TPV.', 'Voer de code van de hoofdgebruiker in. Je account wordt aan zijn bedrijf gekoppeld met alleen kassatoegang.', 'Wpisz kod od głównego użytkownika. Twoje konto dołączy do jego firmy z dostępem tylko do kasy.'],
  'auth.fullName': ['Nombre completo', 'Full name', 'Nom complet', 'Vollständiger Name', 'Nome completo', 'Nome completo', 'Volledige naam', 'Imię i nazwisko'],
  'auth.companyName': ['Nombre de la empresa', 'Business name', 'Nom de l’entreprise', 'Name des Unternehmens', 'Nome dell’azienda', 'Nome da empresa', 'Bedrijfsnaam', 'Nazwa firmy'],
  'auth.email': ['Email', 'Email', 'E-mail', 'E-Mail', 'Email', 'Email', 'E-mail', 'E-mail'],
  'auth.password': ['Contraseña', 'Password', 'Mot de passe', 'Passwort', 'Password', 'Palavra-passe', 'Wachtwoord', 'Hasło'],
  'auth.passwordHint': ['Contraseña (mínimo 8 caracteres)', 'Password (at least 8 characters)', 'Mot de passe (8 caractères minimum)', 'Passwort (mindestens 8 Zeichen)', 'Password (almeno 8 caratteri)', 'Palavra-passe (mínimo 8 caracteres)', 'Wachtwoord (minimaal 8 tekens)', 'Hasło (co najmniej 8 znaków)'],
  'auth.errorEmail': ['Indica un email válido.', 'Enter a valid email.', 'Saisissez un e-mail valide.', 'Gib eine gültige E-Mail ein.', 'Inserisci un’email valida.', 'Indique um email válido.', 'Voer een geldig e-mailadres in.', 'Podaj prawidłowy e-mail.'],
  'auth.errorPassword': ['Indica la contraseña.', 'Enter your password.', 'Saisissez le mot de passe.', 'Gib das Passwort ein.', 'Inserisci la password.', 'Indique a palavra-passe.', 'Voer het wachtwoord in.', 'Podaj hasło.'],
  'auth.errorPasswordLength': ['La contraseña debe tener al menos 8 caracteres.', 'The password must have at least 8 characters.', 'Le mot de passe doit contenir au moins 8 caractères.', 'Das Passwort muss mindestens 8 Zeichen haben.', 'La password deve avere almeno 8 caratteri.', 'A palavra-passe deve ter pelo menos 8 caracteres.', 'Het wachtwoord moet minimaal 8 tekens hebben.', 'Hasło musi mieć co najmniej 8 znaków.'],
  'auth.errorFullName': ['Indica tu nombre completo.', 'Enter your full name.', 'Saisissez votre nom complet.', 'Gib deinen vollständigen Namen ein.', 'Inserisci il tuo nome completo.', 'Indique o seu nome completo.', 'Voer je volledige naam in.', 'Podaj imię i nazwisko.'],
  'auth.errorCompanyName': ['Indica el nombre de la empresa.', 'Enter the business name.', 'Saisissez le nom de l’entreprise.', 'Gib den Namen des Unternehmens ein.', 'Inserisci il nome dell’azienda.', 'Indique o nome da empresa.', 'Voer de bedrijfsnaam in.', 'Podaj nazwę firmy.'],
  'auth.errorCode': ['Introduce el código (mínimo 8 caracteres) que te ha dado el usuario principal.', 'Enter the code (at least 8 characters) the main user gave you.', 'Saisissez le code (8 caractères minimum) fourni par l’utilisateur principal.', 'Gib den Code (mindestens 8 Zeichen) des Hauptbenutzers ein.', 'Inserisci il codice (almeno 8 caratteri) dell’utente principale.', 'Introduza o código (mínimo 8 caracteres) dado pelo utilizador principal.', 'Voer de code (minimaal 8 tekens) van de hoofdgebruiker in.', 'Wpisz kod (co najmniej 8 znaków) od głównego użytkownika.'],
  'auth.errorNoBackend': ['No hay una URL de backend configurada.', 'No backend URL is configured.', 'Aucune URL de serveur n’est configurée.', 'Keine Backend-URL konfiguriert.', 'Nessun URL del server configurato.', 'Não há URL de servidor configurado.', 'Er is geen server-URL ingesteld.', 'Nie skonfigurowano adresu serwera.'],
  'auth.errorGeneric': ['No se pudo completar la operación.', 'The operation could not be completed.', 'L’opération n’a pas pu aboutir.', 'Der Vorgang konnte nicht abgeschlossen werden.', 'Impossibile completare l’operazione.', 'Não foi possível concluir a operação.', 'De bewerking kon niet worden voltooid.', 'Nie udało się wykonać operacji.'],
  'auth.errorNetwork': ['No se pudo conectar con el servidor. Comprueba tu conexión.', 'Could not reach the server. Check your connection.', 'Impossible de joindre le serveur. Vérifiez votre connexion.', 'Server nicht erreichbar. Prüfe deine Verbindung.', 'Impossibile contattare il server. Controlla la connessione.', 'Não foi possível contactar o servidor. Verifique a ligação.', 'Kan de server niet bereiken. Controleer je verbinding.', 'Brak połączenia z serwerem. Sprawdź połączenie.'],
  'auth.errorNoSession': ['El servidor no devolvió una sesión válida.', 'The server did not return a valid session.', 'Le serveur n’a pas renvoyé de session valide.', 'Der Server hat keine gültige Sitzung geliefert.', 'Il server non ha restituito una sessione valida.', 'O servidor não devolveu uma sessão válida.', 'De server gaf geen geldige sessie terug.', 'Serwer nie zwrócił prawidłowej sesji.'],
  'auth.confirmEmailTitle': ['Confirma tu email', 'Confirm your email', 'Confirmez votre e-mail', 'Bestätige deine E-Mail', 'Conferma la tua email', 'Confirme o seu email', 'Bevestig je e-mail', 'Potwierdź e-mail'],
  'auth.confirmEmailMessage': ['Si el email es nuevo, recibirás un correo para activar la cuenta. Después inicia sesión desde este dispositivo.', 'If the email is new, you will receive a message to activate the account. Then sign in from this device.', 'Si l’e-mail est nouveau, vous recevrez un message pour activer le compte. Connectez-vous ensuite depuis cet appareil.', 'Wenn die E-Mail neu ist, erhältst du eine Nachricht zur Aktivierung. Melde dich danach auf diesem Gerät an.', 'Se l’email è nuova, riceverai un messaggio per attivare l’account. Poi accedi da questo dispositivo.', 'Se o email for novo, receberá uma mensagem para ativar a conta. Depois inicie sessão neste dispositivo.', 'Als het e-mailadres nieuw is, ontvang je een bericht om het account te activeren. Log daarna in op dit apparaat.', 'Jeśli e-mail jest nowy, otrzymasz wiadomość aktywacyjną. Następnie zaloguj się na tym urządzeniu.'],
  'auth.conflictTitle': ['Sesión ya abierta', 'Session already open', 'Session déjà ouverte', 'Sitzung bereits geöffnet', 'Sessione già aperta', 'Sessão já aberta', 'Sessie al geopend', 'Sesja już otwarta'],
  'auth.conflictMessage': ['La cuenta ya está abierta en otro dispositivo. Si la abres aquí, el otro dispositivo se cerrará.', 'The account is already open on another device. If you open it here, the other device will be signed out.', 'Le compte est déjà ouvert sur un autre appareil. Si vous l’ouvrez ici, l’autre appareil sera déconnecté.', 'Das Konto ist bereits auf einem anderen Gerät geöffnet. Wenn du es hier öffnest, wird das andere Gerät abgemeldet.', 'L’account è già aperto su un altro dispositivo. Se lo apri qui, l’altro dispositivo verrà disconnesso.', 'A conta já está aberta noutro dispositivo. Se a abrir aqui, o outro dispositivo será desligado.', 'Het account is al geopend op een ander apparaat. Als je het hier opent, wordt het andere apparaat afgemeld.', 'Konto jest już otwarte na innym urządzeniu. Jeśli otworzysz je tutaj, drugie urządzenie zostanie wylogowane.'],
  'auth.conflictCancel': ['Cancelar', 'Cancel', 'Annuler', 'Abbrechen', 'Annulla', 'Cancelar', 'Annuleren', 'Anuluj'],
  'auth.conflictTransfer': ['Abrir en este dispositivo', 'Open on this device', 'Ouvrir sur cet appareil', 'Auf diesem Gerät öffnen', 'Apri su questo dispositivo', 'Abrir neste dispositivo', 'Op dit apparaat openen', 'Otwórz na tym urządzeniu'],
  'auth.sessionMovedTitle': ['Sesión cerrada', 'Signed out', 'Session fermée', 'Abgemeldet', 'Sessione chiusa', 'Sessão terminada', 'Afgemeld', 'Wylogowano'],
  'auth.sessionMovedMessage': ['Tu cuenta se ha abierto en otro dispositivo y esta sesión se ha cerrado.', 'Your account was opened on another device and this session has been closed.', 'Votre compte a été ouvert sur un autre appareil et cette session a été fermée.', 'Dein Konto wurde auf einem anderen Gerät geöffnet und diese Sitzung wurde beendet.', 'Il tuo account è stato aperto su un altro dispositivo e questa sessione è stata chiusa.', 'A sua conta foi aberta noutro dispositivo e esta sessão foi terminada.', 'Je account is op een ander apparaat geopend en deze sessie is gesloten.', 'Twoje konto otwarto na innym urządzeniu i ta sesja została zamknięta.'],
};

const locales: AppLocale[] = ['es', 'en', 'fr', 'de', 'it', 'pt', 'nl', 'pl'];
export const authTranslations = Object.fromEntries(locales.map((locale, index) => [
  locale, Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values[index]])),
])) as Record<AppLocale, Record<string, string>>;
