-- Tabla para sincronizar el historial de gastos de la app (recuperación tras borrar datos,
-- móvil nuevo o avería). Ejecutar en Supabase: Dashboard -> SQL Editor -> pegar y Run.
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  local_id text not null,
  based_on text not null default 'client',
  description text not null default '',
  amount numeric not null default 0,
  date date,
  category text not null default 'Otros',
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, local_id, based_on)
);

alter table public.expenses enable row level security;

-- Cada usuario solo puede ver y gestionar sus propios gastos (el backend usa la clave service,
-- que ignora RLS, pero la política protege el acceso directo desde clientes con anon key).
create policy "Users manage own expenses"
  on public.expenses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- El backend guarda y lee los gastos con la clave secreta (rol service_role). Sin estos permisos
-- Supabase responde 42501 "permission denied for table expenses" y el historial de gastos no
-- se guarda ni se puede recuperar.
grant usage on schema public to service_role;
grant select, insert, update, delete on public.expenses to service_role;
grant usage, select on sequence public.expenses_id_seq to service_role;
