-- =====================================================================================
-- DIAGNOSTICO: por que el backend sigue devolviendo "permission denied for table ..."?
-- Ejecuta este bloque en Supabase -> SQL Editor -> Run. Es solo lectura: no cambia nada.
-- =====================================================================================

-- A) ¿EXISTEN las tablas que usa el backend? (documents y expenses)
select table_name
  from information_schema.tables
 where table_schema = 'public'
   and table_name in ('documents', 'expenses')
 order by table_name;
-- Si solo aparece 'documents' o no aparece 'expenses', el SQL del paso 1 no se ejecuto
-- en ESTE proyecto: ejecuta de nuevo server/supabase-expenses.sql aqui.

-- B) ¿QUE ROL USA EL BACKEND? Esta es la clave del problema.
--    El backend se conecta con SUPABASE_SECRET_KEY. Si en Render esa variable contiene
--    la clave 'anon' o la 'publishable' en vez de la 'service_role' / 'sb_secret_...',
--    Supabase la trata como usuario sin privilegios y devuelve 42501 aunque los grants
--    esten aplicados. Esta consulta no lo puede ver (depende de la clave), asi que
--    compruebalo tu en el panel de Render (ver nota de abajo).
--
-- C) ¿TIENEN PERMISOS los roles que usa Supabase por defecto?
select
  grantee,
  table_name,
  string_agg(privilege_type, ', ' order by privilege_type) as permisos
  from information_schema.role_table_grants
 where table_schema = 'public'
   and table_name in ('documents', 'expenses')
   and grantee in ('service_role', 'anon', 'authenticated', 'postgres')
 group by grantee, table_name
 order by table_name, grantee;
-- Referencia de lo correcto:
--   documents  -> service_role: INSERT, SELECT, UPDATE, DELETE (+ postgres)
--   expenses   -> service_role: INSERT, SELECT, UPDATE, DELETE (+ postgres)
-- Si 'service_role' NO aparece, los grants no se aplicaron a esta tabla.
-- Si 'service_role' aparece y aun asi falla -> la clave de Render no es la de service_role.

-- D) ¿ESTAN ACTIVAS LAS POLITICAS RLS? (no es el problema actual, pero conviene verlo)
select tablename, rowsecurity, forcerowsecurity
  from pg_tables
 where schemaname = 'public'
   and tablename in ('documents', 'expenses')
 order by tablename;
-- rowsecurity = true es lo normal: service_role las ignora, asi que no es la causa.

-- E) COMPROBACION FINAL de permisos, como los ve el backend:
select has_table_privilege('service_role', 'public.documents', 'INSERT') as doc_insert,
       has_table_privilege('service_role', 'public.documents', 'SELECT') as doc_select,
       has_table_privilege('service_role', 'public.expenses',  'INSERT') as exp_insert,
       has_table_privilege('service_role', 'public.expenses',  'SELECT') as exp_select;
-- Las 4 deben ser true. Si son false, vuelve a ejecutar el bloque de permisos de abajo.
-- =====================================================================================


-- =====================================================================================
-- REPARACION (ejecuta solo si la consulta E sale con algun false, o si en A falta 'expenses')
-- =====================================================================================
begin;

-- 1) La tabla de gastos (idempotente).
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  local_id text not null,
  based_on text not null default 'client',
  description text not null default '',
  amount numeric not null default 0,
  date date,
  category text not null default 'Otros',
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, local_id, based_on)
);

-- 2) Columnas que necesita el backend en documents.
alter table public.documents
  add column if not exists user_id uuid references auth.users (id) on delete set null;
alter table public.documents
  add column if not exists updated_at timestamptz not null default now();

create index if not exists documents_user_id_created_at_idx
  on public.documents (user_id, created_at desc);

-- 3) RLS + politica de gastos (se elimina antes para poder repetir el script).
alter table public.expenses enable row level security;
drop policy if exists "Users manage own expenses" on public.expenses;
create policy "Users manage own expenses"
  on public.expenses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 4) PERMISOS: esta es la parte que resuelve el error. 'service_role' es el rol del
--    backend (si en Render usas la clave secreta nueva, el rol se llama 'service_role'
--    igualmente, asi que el grant sigue siendo valido).
grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
-- Grants explicitos por tabla, por si 'all on all tables' se quedo corto.
grant select, insert, update, delete on public.documents to service_role;
grant select, insert, update, delete on public.expenses  to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;

-- Debe devolver las 4 columnas en true.
select has_table_privilege('service_role', 'public.documents', 'INSERT') as doc_insert,
       has_table_privilege('service_role', 'public.documents', 'SELECT') as doc_select,
       has_table_privilege('service_role', 'public.expenses',  'INSERT') as exp_insert,
       has_table_privilege('service_role', 'public.expenses',  'SELECT') as exp_select;
